### PR TITLE
Sleep one second between calls to now()

### LINKED ISSUE #1896: test_early_times_err fails
```rust
[  661s] ---- engine::strat_engine::backstore::metadata::bda::tests::test_early_times_err stdout ----
[  661s] thread 'engine::strat_engine::backstore::metadata::bda::tests::test_early_times_err' panicked at 'assertion failed: `(left != right)`
[  661s]   left: `2020-03-24T06:09:36.646479850Z`,
[  661s]  right: `2020-03-24T06:09:36.646479850Z`', src/engine/strat_engine/backstore/metadata/bda.rs:197:9
[  661s] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Just tried to build latest fedora package again... Any ideas what could be the reason?

### PR DESCRIPTION
**Pull request by mulkieran**
closes #1896

### CODE REVIEW

**Comment by mulkieran** [comment]
rebased.

File: src/engine/strat_engine/backstore/metadata/bda.rs [hunk 1]
```diff
@@ -187,8 +188,8 @@ mod tests {
         .unwrap();
 
         let timestamp0 = Utc::now();
+        thread::sleep(sleep_time);
         let timestamp1 = Utc::now();
-        assert_ne!(timestamp0, timestamp1);
```
Comment (jbaublitz) [inline src/engine/strat_engine/backstore/metadata/bda.rs]: Just one question before I approve this. As I recall from reading the metadata document, if both times are the same, one timestamp is incremented, correct? So is this why we don't need to assert that they're different?

Comment (mulkieran) [reply src/engine/strat_engine/backstore/metadata/bda.rs]: I have decided to trust the sleep() guarantee implicitly, that 1 second must elapse between calls. The assertion was there before because I had a hunch that the problem we're encountering now might sometime occur, that it wasn't absolutely guaranteed not to occur...and since the test wouldn't work w/out it, an assert was appropriate.
