### PR TITLE
Issue stratisd 3086 v2

### LINKED ISSUE #3086: assertion failed: datablocks_to_sectors(upper_data_aligned) + upper_limit_meta_size * 2u64 > total_space
I just upgraded to Stratis 3.2.1 yesterday, and while working with some files today (basic operations, just updating the cover art on some music files), all I/O completely froze & I got this error in the journal:

```
Aug 17 09:45:54 hp-fedora stratisd[1732]: thread 'stratis-wt-657' panicked at 'assertion failed: datablocks_to_sectors(upper_data_aligned) + upper_limit_meta_size * 2u64 >\n    total_space', src/engine/strat_engine/thinpool/thinpool.rs:303:5
Aug 17 09:45:54 hp-fedora stratisd[1732]: stack backtrace:
Aug 17 09:45:54 hp-fedora stratisd[1732]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aug 17 09:45:54 hp-fedora stratisd[1732]: [2022-08-17T14:45:54Z WARN  stratisd::engine::strat_engine::engine] Failed to get status for thread handling filesystem checks: task 1301 panicked
```

I'm...admittedly not sure how to debug this, I'm guessing there's some FS metadata or similar that would help?

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes #3086 
Alternative to #3088

### CODE REVIEW

File: src/engine/strat_engine/thinpool/thinpool.rs [hunk 1]
```diff
@@ -257,9 +267,9 @@ fn search(
         assert!(lower_limit_sectors + lower_meta * 2u64 <= total_space);
         Ok((lower_limit_sectors, lower_meta))
     } else if datablocks_to_sectors(half) + half_meta * 2u64 > total_space {
```
Comment (mulkieran) [inline src/engine/strat_engine/thinpool/thinpool.rs:269]: suggest extra condition here to allow for the unlikely possibility that ```current_data_size``` > than optimum data size.

```
if datablocks_to_sectors(half) + half_meta * 2u64 > total_space && half > current_data_size { ...
```

File: src/engine/strat_engine/thinpool/thinpool.rs [hunk 2]
```diff
@@ -234,17 +234,27 @@ fn search(
...
 ) -> StratisResult<(Sectors, Sectors)> {
     let diff = upper_limit - lower_limit;
     let half = lower_limit + diff / 2u64 + diff % 2u64;
-    let half_meta = thin_metadata_size(DATA_BLOCK_SIZE, datablocks_to_sectors(half), fs_limit)?;
+    let half_meta = max(
+        thin_metadata_size(DATA_BLOCK_SIZE, datablocks_to_sectors(half), fs_limit)?,
+        current_meta_size,
+    );
 
     if diff == DataBlocks(1) {
```
Comment (mulkieran) [inline src/engine/strat_engine/thinpool/thinpool.rs:247]: suggest additional distinct termination condition in case ```current_data_size``` > than optimum data size.

```
if half == current_data_size {
    Ok((current_data_size, (total - current_data_size) / 2))
}
```

**Review by mulkieran — CHANGES_REQUESTED** [review]
I think the algorithm looks quite robust for the previously identified thin metadata problem. I propose a way of hardening it against the not yet observed thin data size too large for optimum problem as well.

File: src/engine/strat_engine/thinpool/thinpool.rs (hunk 2 above)
Comment (mulkieran) [reply src/engine/strat_engine/thinpool/thinpool.rs:247]: > suggest additional distinct termination condition in case `current_data_size` > than optimum data size.
> 
> ```
> if half == current_data_size {
>     Ok((current_data_size, (total - current_data_size) / 2))
> }
> ```
Thinking you should return an error here, because metadata size can not be enough.

Comment (mulkieran) [reply src/engine/strat_engine/thinpool/thinpool.rs:247]: But also thinking that an error is wrong, because in the usual overprovisioned case, even if the metadata is not enough, then you still want to expand. Otoh, in the switch to no-overprovisioned calculation, I think you want to reject the result, because there isn't room enough for the metadata. So, maybe it would be best to enrich the return type somehow.

**Comment by jbaublitz** [comment]
Okay I think this should resolve the issue!

**Review by mulkieran — CHANGES_REQUESTED** [review]
Please look at use of ```min_datadev_size()``` in ```check_fs()```. I believe that the change as it stands will mean that the ```current_data_size``` will never be chosen in the max operation. Maybe ```search()``` should return ```Result<Option<(Sectors, Sectors)>>```.

**Comment by mulkieran** [comment]
> Please look at use of `min_datadev_size()` in `check_fs()`. I believe that the change as it stands will mean that the `current_data_size` will never be chosen in the max operation. Maybe `search()` should return `Result<Option<(Sectors, Sectors)>>`.

And then maybe ```min_datadev_size()``` could use the info to simply return the max of the search result or the current data size.

**Comment by mulkieran** [comment]
> > Please look at use of `min_datadev_size()` in `check_fs()`. I believe that the change as it stands will mean that the `current_data_size` will never be chosen in the max operation. Maybe `search()` should return `Result<Option<(Sectors, Sectors)>>`.
> 
> And then maybe `min_datadev_size()` could use the info to simply return the max of the search result or the current data size.

@jbaublitz: Also need to fix up dependencies for test failures.

**Review by mulkieran — APPROVED** [review]

**Comment by refi64** [comment]
Just tested and confirmed this fixes my issue!
