### PR TITLE
Fix property calculation for TotalPhysicalUsed

### LINKED ISSUE #2860: PropertiesChanged signal value incorrect for TotalPhysicalUsed when FS is created
When you create a FS, the client gets the `InterfacesAdded` signal with the newly created FS object.  Shortly afterwards a `PropertiesChanged` signal is received for the pool it was created from, with an updated value of `TotalPhysicalUsed`.  However, this value does not match what is retrieved when we fetch the property.

```
# dbus-monitor --system "type='signal',sender='org.storage.stratis3'"
signal time=1638383931.637890 sender=org.freedesktop.DBus -> destination=:1.371 serial=4294967295 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.371"
signal time=1638383931.637905 sender=org.freedesktop.DBus -> destination=:1.371 serial=4294967295 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.371"
signal time=1638383960.823658 sender=:1.191 -> destination=(null destination) serial=1439 path=/org/storage/stratis3; interface=org.freedesktop.DBus.ObjectManager; member=InterfacesAdded
   object path "/org/storage/stratis3/79"
   array [
      dict entry(
         string "org.storage.stratis3.filesystem.r0"
         array [
            dict entry(
               string "Created"
               variant                   string "2021-12-01T18:39:20Z"
            )
            dict entry(
               string "Pool"
               variant                   object path "/org/storage/stratis3/75"
            )
            dict entry(
               string "Uuid"
               variant                   string "09cc8d1a065b4f31ae16fa09e41ba0aa"
            )
            dict entry(
               string "Name"
               variant                   string "testfs0"
            )
            dict entry(
               string "Used"
               variant                   struct {
                     boolean true
                     string "572522496"
                  }
            )
            dict entry(
               string "Size"
               variant                   string "1099511627776"
            )
            dict entry(
               string "Devnode"
               variant                   string "/dev/stratis/testpool/testfs0"
            )
         ]
      )
   ]
signal time=1638383960.823808 sender=:1.191 -> destination=(null destination) serial=1440 path=/org/storage/stratis3/75; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "org.storage.stratis3.pool.r0"
   array [
      dict entry(
         string "TotalPhysicalUsed"
         variant             struct {
               boolean true
               string "607805440"
            }
      )
   ]
   array [
   ]
```

```
# dbus-send --system --dest=org.storage.stratis3 --print-reply /org/storage/stratis3/75 org.freedesktop.DBus.Properties.GetAll  string:org.storage.stratis3.pool.r0
method return time=1638386288.240130 sender=:1.191 -> destination=:1.403 serial=1468 reply_serial=2
   array [
      dict entry(
         string "AllocatedSize"
         variant             string "2147483648"
      )
      dict entry(
         string "AvailableActions"
         variant             string "fully_operational"
      )
      dict entry(
         string "ClevisInfo"
         variant             struct {
               boolean true
               struct {
                  boolean false
                  struct {
                     string ""
                     string ""
                  }
               }
            }
      )
      dict entry(
         string "Encrypted"
         variant             boolean false
      )
      dict entry(
         string "HasCache"
         variant             boolean false
      )
      dict entry(
         string "KeyDescription"
         variant             struct {
               boolean true
               struct {
                  boolean false
                  string ""
               }
            }
      )
      dict entry(
         string "Name"
         variant             string "testpool"
      )
      dict entry(
         string "TotalPhysicalSize"
         variant             string "2147483648"
      )
      dict entry(
         string "TotalPhysicalUsed"
         variant             struct {
               boolean true
               string "616194048"
            }
      )
      dict entry(
         string "Uuid"
         variant             string "64654c59be7847c5aa5a1eb6d261e715"
      )
   ]
```

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes #2860

@tasleson If you'd like, please confirm that this resolves this issue. I tested it on my end, but I'm happy to have you double check!

### CODE REVIEW

**Comment by tasleson** [comment]
@jbaublitz I'll give it a try, likely tomorrow and I'll let you know, thanks

**Comment by jbaublitz** [comment]
Perfect, sounds great!

File: src/engine/strat_engine/thinpool/thinpool.rs [hunk 1]
```diff
@@ -533,7 +533,10 @@ impl ThinPool {
         );
 
         let original_state = self.cached(|pool| ThinPoolState {
-            usage: pool.total_physical_used().map(|s| s.bytes()).ok(),
+            usage: pool
```
Comment (mulkieran) [inline src/engine/strat_engine/thinpool/thinpool.rs:536]: Looks right to me. Could you abstract this expression into a method in the thinpool and make ```StratPool::total_physical_used()``` call that method? I'm worried about the two code locations getting out of sync again, otherwise.

**Review by mulkieran — CHANGES_REQUESTED** [review]

**Comment by tasleson** [comment]
> Perfect, sounds great!

Tested and found to correct this issue, thanks.

File: src/engine/strat_engine/thinpool/thinpool.rs (hunk 1 above)
Comment (jbaublitz) [reply src/engine/strat_engine/thinpool/thinpool.rs:536]: That sounds reasonable to me. I was considering that when I saw the note above the implementation in `pool.rs`.

**Comment by jbaublitz** [comment]
> > Perfect, sounds great!
> 
> Tested and found to correct this issue, thanks.

Wonderful! I'll make the PR revisions and then we can merge it.

File: src/engine/strat_engine/thinpool/thinpool.rs (hunk 1 above)
Comment (jbaublitz) [reply src/engine/strat_engine/thinpool/thinpool.rs]: Resolved!

**Review by mulkieran — APPROVED** [review]
